# 数据库迁移配置文件
source_database:
  type: "sqlite"
  connection:
    database: "D:/Programs/chatSpace/backend/database/app.db"

target_database:
  type: "sqlserver"
  connection:
    server: "Localhost"
    database: "test_base"
    username: "zhuo"
    password: "123456"
    port: 1433
    driver: "ODBC Driver 17 for SQL Server"

# 迁移设置
migration_settings:
  # 批处理大小，避免内存溢出
  batch_size: 1000
  
  # 是否在迁移前清空目标表
  truncate_target_tables: false
  
  # 是否创建目标表（如果不存在）
  create_target_tables: true
  
  # 是否保持原始表结构
  preserve_schema: true
  
  # 数据类型映射
  type_mappings:
    TEXT: "NVARCHAR(MAX)"
    VARCHAR: "NVARCHAR(MAX)"
    INTEGER: "INT"
    REAL: "FLOAT"
    BLOB: "VARBINARY(MAX)"
    DATETIME: "DATETIME2"
    BOOLEAN: "BIT"

# 表配置
tables:
  # 要迁移的表列表，如果为空则迁移所有表
  include_tables: []
  
  # 要排除的表列表
  exclude_tables: []
  
  # 表名映射（源表名 -> 目标表名）
  table_mappings: {}

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "migration.log" 